### ISSUE TITLE
Support for Silkeborg Forsyning

### ISSUE THREAD

**Issue by skafsgaar** [kpoppel/homeassistant-novafos#1]
Silkeborg Forsyning also uses the KMD platform for showing usage, however I can't find the supplier ID by inspecting the website. Is there another way that you know of for finding this?

**Comment by kpoppel** [comment]
Hi @skafsgaar .  I think Silkeborg would be: https://minforsyning.kmd.dk/Login.aspx?plant=179&utility=1

So 179 is the plant.  You can try 179000 as the supplier ID.

It seems Silkeborg uses "https://minforsyning.kmd.dk/", whereas my local one uses "https://minforsyning-2.kmd.dk/", so there might be a difference here.

Obviously I have no way to test this with anything else than my own login.  If it works, feel free to submit a merge request with your findings to improve the README.md file.

**Comment by kpoppel** [comment]
Closed due to inactivity.
