### ISSUE TITLE
V3.0.1 I removed the integration and its not possible to add it again.

### ISSUE THREAD

**Issue by kpoppel** [kpoppel/homeassistant-novafos#11]
I removed the integration and its not possible to add it again.

_Originally posted by @Sdahl1234 in https://github.com/kpoppel/homeassistant-novafos/issues/10#issuecomment-1250134759_

**Comment by kpoppel** [comment]
@sdahl1234, the one thing I did not test because I just made an upgrade path 😊

Can you tell what happens?

**Comment by Sdahl1234** [comment]
I got this. Nothing in the log at all
![image](https://user-images.githubusercontent.com/80645006/190876565-05c89fac-f686-41e7-89ed-842dcd9dec28.png)

**Comment by kpoppel** [comment]
Thanks. I'll look into that.

**Comment by Sdahl1234** [comment]
Now its possible to add the integration again. thanks. BUT it seems my token has a length of 1502 and its not valid.

I have this in my log after adding the token and reloaded

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.novafos.pynovafos.novafos
Source: custom_components/novafos/pynovafos/novafos.py:84
Integration: Novafos (documentation, issues)
First occurred: 14.59.47 (3 occurrences)
Last logged: 15.04.39

Token update does not seem to have a valid length. Please check again. (This message is normal the first time the integration starts)

**Comment by Sdahl1234** [comment]
I tried to change the length check to 1502 but i do not get any data

![image](https://user-images.githubusercontent.com/80645006/190904774-05fdc859-b67d-48b6-9384-775cf64d532d.png)

I will try with debug later today

**Comment by kpoppel** [comment]
Now set to 1200 :-)  If you configure the integration and use the token, then data should update.

**Comment by Sdahl1234** [comment]
It does not update data. Only last valid date and its 2 hours ahead of now

**Comment by Sdahl1234** [comment]
Hmm. Now its updating. reboot HA and it is working again.
