### ISSUE TITLE
Supplier ID is 7 digits

### ISSUE THREAD

**Issue by digidolphin** [kpoppel/homeassistant-novafos#14]
The documentation says to fetch 6-digit the supplier id. Unfortunately I can see mine is 7 (0676000). I have tried using that, I've tried 676000 and 067600, but neither works. I get no errors, but there are no entities created, so I'm getting no data. I am logging in using e-mail/pwd combo - it doesn't seem to be documented, so this could also be the reason for not being able to login. Any input?

**Comment by kpoppel** [comment]
Yes, I am pretty sure email/pass is a different authentication flow from customer id/pin. The supplier Id shokld not be the issue as this data is just used exactly as types towards the Api.
