### ISSUE TITLE
Not an issue - but confirmed to work with Skanderborg Forsyning

### ISSUE THREAD

**Issue by larserhardsen** [kpoppel/homeassistant-novafos#8]
Hi,

just wanted to inform you that your integration works with Skanderborg Forsyning as well :)

-Lars

**Comment by kpoppel** [comment]
Hi Lars.  Thanks for letting me know!

**Comment by ressel87** [comment]
It also works with BEOF - Bornholms energi og forsyning. would be nice if it also could fetch data from heating (fjernvarme)

**Comment by PexJensen** [comment]
Also works with NFS (Nyborg Forsyning)

Also i would like it to fetch the heating.

**Comment by kpoppel** [comment]
Thanks for letting me know!  I am willing to look into getting heating data as well. In that case I would need to borrow a set of credentials to be able to investigate what the API endpoints looks like, and the data returned looks like for heating.
If you are okay with that, you can send this to me here: kpoppel.at.github@gmail.com .  

The general rule is to never send credentials to anyone on the Internet, so only do this if you think you can trust that I will keep your credentials and data safe and delete them once the work is completed (which is what I will do obviously).
